version: '3'

services:
  app:
    container_name: douban-crawler-app
    build:
      context: "."
    restart: "no"
    environment:
      PROXY_POOL_HOST: http://douban-crawler-proxy-pool:5010
      DB_HOST: douban-crawler-db
      DB_USER: crawler
      DB_PASS: crawler
      DB_NAME: crawler
    networks:
      - douban-crawler
      - douban-crawler-db

networks:
  douban-crawler:
  douban-crawler-db:

