version: '3'

services:
  app:
    container_name: douban-crawler-app
    build:
      context: "."
    restart: "no"
    environment:
      PROXY_POOL_HOST: http://douban-crawler-proxy-pool:5010
    volumes:
      - ./_data:/data
    networks:
      - douban-crawler

networks:
  douban-crawler:

volumes:
  _data:
